services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/app
    environment:
      DATABASE_URL: mysql://root:@database:3306/rust_api
    ports:
      - "8080:8080"
    depends_on:
      - database
    command: /bin/sh -c "dockerize -wait tcp://database:3306 && cargo watch -x 'run --bin rust-api'"
  database:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "rust_api"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
