name: Build

on: [push]

jobs:
  format_check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run format check
        run: cargo fmt --all -- --check
